name: Auto Change DialogWeb-Vi-En

on:
  workflow_dispatch:
  schedule:
    - cron: '*/1 * * * *'

jobs:
  auto_change:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Modify DialogWeb-Vi-En
        run: |
          CONTENT=$(cat DialogWeb-Vi-En)
          RANDOM_STRING=$(echo "00000")
          NEW_CONTENT="${CONTENT:0:-5}${RANDOM_STRING}"
          echo "$NEW_CONTENT" > DialogWeb-Vi-En

      - name: Add Commit
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git remote set-url origin https://x-access-token:${{ secrets.TOKEN }}@github.com/HuynhNgoc2709/CheckUpdateAppMod
          git add DialogWeb-Vi-En
          git commit -m "Auto change DialogWeb-Vi-En"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.TOKEN }}
          
